apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  namespace: anotherclass-321
  name: api-tester-3211
rules:
  - apiGroups: ["*"]
    resources: ["pods", "services", "deployments"]  # 복수로 사용 kubectl api-resources
    verbs: ["get", "list"]  # "get", "list", "watch", "create", "update", "patch", "delete"