apiVersion: v1
kind: Secret
metadata:
  namespace: anotherclass-323
  name: api-tester-3231-postgresql
  labels:
    part-of: k8s-anotherclass
    component: backend-server
    name: api-tester
    instance: api-tester-3231
    version: 3.0.0
    managed-by: kubectl
stringData:
  postgresql-info.yaml: |
    driver-class-name: "org.postgresql.Driver"
    url: "jdbc:postgresql://postgresql:5431"
    username: "dev"
    password: "dev123"
