apiVersion: v1
kind: Service
metadata:
  namespace: anotherclass-322
  name: database-headless
  labels:
    part-of: k8s-anotherclass
    component: database
    name: database
    instance: database
    version: 3.0.0
    managed-by: kubectl
spec:
  selector:
    part-of: k8s-anotherclass
    component: database
    name: database
    instance: database
  type: ClusterIP
  clusterIP: None