apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: shared-volume-3231
  namespace: anotherclass-323
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 1G
  storageClassName: ""
  selector:
    matchLabels:
      part-of: k8s-anotherclass
      component: backend-server
      name: api-tester
      instance: application-3231